### ISSUE TITLE
Definir solução intermediaria Arduino

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#105]
COnstruir emulador do Arduino visando realizar os testes das funcionalidades do Issues Monitoring. Este emulador deve realizar a API projetada para o Arduino e realizar a comunicaco com o Issues Monitoring. 
Realizar o envio de dados de temperatura e umidade contendo valores distintos e aleatorios, com submissao de valores extremos (limite superior e inferior) visando observar capacidade de deteccao do sistema.

**Comment by Lucas-CG** [comment]
Adicionei um emulador à branch _development_. Resta testar com o Servidor para ver se opera OK.

**Comment by yagoocarvalho** [comment]
Emulador do arduino rodando
