### ISSUE TITLE
Executar os testes sistemicos

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#106]
Com base nos planos de teste atualizados e revisados, executar os testes. Esta tarefa NAO deve ser realizada pela Silvia.

**Comment by Lucas-CG** [comment]
Testes
IM-32: Gerenciar Usuário do Sistema Autorizado 
IM-53: Gerenciar Usuário do Sistema 
IM-55: Gerenciar Usuário do Sistema Administrador 
IM-56: Gerenciar Usuário do Sistema não autorizado como Administrador 
IM-57: Gerenciar Usuário do Sistema não Autorizado 
IM-58: Gerenciar Usuário do Sistema desautorizado como Administrador

realizados. O sistema passou nestes, e os resultados estão no TestLink.
