### ISSUE TITLE
Manter registro de usuários do Issues Monitoring

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#11]
Ator: Servidor

- [x] Servidor armazena no banco de dados toda atualização de informação de usuários, para garantir a persistencia dos dados.

- [x] Servidor obtém informações do banco de dados quando necessário acessá-las.

- [x] TESTADO

**Comment by deborabpina** [comment]
Teste feito para o Cadastro do usuário. Verificar plano de teste disponível.
