### ISSUE TITLE
Icones de erro devem ser ajustados e feitos consistentes

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#124]
Reduzir o tamanho dos icones de erro e coloca-los consistentes em todas as informações de erro.

**Comment by cemarciano** [comment]
Aumentei o tamanho da imagem de Erro 404 em 10%, a fim de torná-la de tamanho mais similar ao do Erro 500. Porém, mantive imagens diferentes a fim de facilitar a identificação do tipo do erro de forma mais rápida pelo usuário que, conhecendo a imagem, já sabe o tipo de erro que ele está enfrentando.
