### ISSUE TITLE
Manter dados do laboratório

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#13]
Ator: Servidor

- [x] Servidor armazena no banco de dados toda atualização de informação do laboratório, para garantir a persistencia dos dados.

- [x] Servidor obtém informações do banco de dados quando necessário acessá-las.

- [x] TESTADO

**Comment by deborabpina** [comment]
Teste realizado para criação e edição de informações de um laboratório.
