### ISSUE TITLE
Identificar anomalias e notificar usuários

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#15]
Ator: Servidor

- [x] Servidor identifica que alguma (ou todas) condição de ambiente informada pelo arduino está fora da zona de conforto
- [x] Servidor recupera no repositório usuários autenticados no laboratório (isto é, que estejam presentes no laboratório)
- [x] Servidor envia e-mail aos usuários identificados no passo anterior informando as condições e requisitando que o problema seja resolvido.
- [x] TESTADO

**Comment by deborabpina** [comment]
No caso de não haver usuários presentes no laboratório, podemos enviar email para os administradores (no caso, o responsável pelo laboratório)?

**Comment by jeronimohjr** [comment]
Seria interessante que em casos de anormalidades, um e-mail de notificação fosse enviado para os presentes e tbm para o responsável do laboratório. Se ninguém estiver presente, a notificação pode ser enviada somente para o(s) responsável(is).

**Comment by deborabpina** [comment]
Excelente! Está feito dessa forma então: envia para presentes e responsável; no caso de não haver presentes, envia para o responsável.

**Comment by deborabpina** [comment]
A checagem das condições de ambiente ocorrem com que intervalo de tempo? O mesmo intervalo considerado pelo arduino?

**Comment by jeronimohjr** [comment]
Acho que o mais coerente é permitir que esse intervalo de checagem possa ser configurado.
