### ISSUE TITLE
Analisar graficamente os dados das Condições de Ambiente

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#19]
Ator: Web

- [x] Usuário do Sistema seleciona o botão “Gerar gráficos, indo para uma página referente a essa funcionalidade. 

- [x] Servidor obtém equipamentos do laboratório

- [x] O usuário escolhe o tipo de gráfico (temperatura, luminosidade, etc) e o intervalo desejado, enviando uma requisição de histórico de dados para o servidor.

- [x] O usuário escolhe se quer gráfico do laboratório ou de um equipamento do laboratório.

- [x] Ao receber essas informações, o sistema web gera o gráfico e apresenta ao usuário

- [x] TESTADO

**Comment by deborabpina** [comment]
https://developers.google.com/chart/interactive/docs/gallery/intervals#combining-interval-styles

**Comment by yagoocarvalho** [comment]
usar gráfico Points and whiskers
