### ISSUE TITLE
Parser lê email, amarzenando evento no servidor

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#20]
- [x] Parser checa periodicamente (período configurável via página web) se há mensagens não lidas.
- [x] Caso haja, Parser deve coletar uma cópia dessas mensagens e marcá-las como lida.
- [x] Parser deve varrer as mensagens procurando pela Tag que indica o início da mensagem a ser parseada e pela data e hora do evento.
- [x] Parser interpreta o conteúdo da mensagem a partir da Tag do evento com user_id (opcional) de quem o causou (lista de eventos a ser definida baseado nos eventos que forem captados pelo MyDenox; formato do user_id: “1ª letra nome usuário + 3 primeiras letras primeiro sobrenome usuário.” Exs: ghor(Guilherme Horta), ador(Andréa Doreste);
- [x] Parser salva no Banco de Dados (através da API do Servidor) o resultado de sua interpretação.
- [x] TESTADO

**Comment by yagoocarvalho** [comment]
https://docs.python.org/3/library/unittest.html
