### ISSUE TITLE
Falha de comunicação com o Servidor

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#22]
- [x] Parser não consegue se comunicar com o Servidor.
- [x] Parser acessa o servidor IMAP e marca os e-mails parseados, mas não enviados, como não lidos.
- [ ] Notificar Usuários presentes no laboratório e Usuários de Sistema sobre falha de comunicação
- [x] TESTADO

**Comment by paulocsanz** [comment]
Para notificar os usuários presentes sobre uma falha de conexão/autenticação com o servidor IMAP é necessário conectar ao servidor SMTP e realizar a autenticação.

Se um falhou não vejo razão para o outro não falhar.

Qual a sugestão? Tentar enviar mesmo assim? Porque a falha ou é por senha incorreta (que só ocorrerá se alguém modificar a senha e ocorrerá no envio da mesma forma ou de falha ao acessar a internet. Como o parser faz parte do servidor, isso significa que ele está completamente inacessível.

**Comment by ghtravassos** [comment]
Registrar como anomalia (falha de servidor IMAP). Informar para contactar o suporte para resolver o problema. Nao enviar mensagem neste caso.
