### ISSUE TITLE
Identificar se há luz acesa e notificar responsável (Servidor)

### ISSUE THREAD

**Issue by deborabpina** [ESEGroup/IssuesMonitoring#25]
- [x] Repetir issue em intervalo de tempo pré-determinado
- [x] Checa se existe alguém no laboratório 
- [x] Checar se há luz acesa
- [x] Informar responsável do laboratório que há luzes acesas
- [x] Informar último usuário que registrou sua saída do laboratório
- [x] TESTADO

**Comment by deborabpina** [comment]
Isso é checado em que intervalo de tempo? O mesmo intervalo considerado pelo arduino?

**Comment by jeronimohjr** [comment]
Tem que analisar o contexto escrito no escopo do projeto. Seria interessante  configurar os dias da semana e horários para essa checagem. Exemplos: 
Opções de dias um ckeckbox
( ) Todos dias da semana  ( ) Segunda.....   ( ) Sábado  ( ) Domingo
Opções de horários em um radio button
 (  ) 00:00     ( ) 01:00 ....

* Obs: pensar se seria viável definir mais de uma opção de checagem.

**Comment by yagoocarvalho** [comment]
acho que seria interessante a cada envio do arduino, pois se o intervalo for diferente do do arduino pode haver inconsistência nos alarmes. Podemos implementar de forma que quando o arduino envia os dados, checa se há anomalia ao mesmo tempo da gravação no banco
