### ISSUE TITLE
Registrar dados do Arduino no banco de dados

### ISSUE THREAD

**Issue by deborabpina** [ESEGroup/IssuesMonitoring#26]
- [x] Servidor recebe dados do arduino através da API
- [x] Servidor autentica o arduino conferindo o endereço MAC enviado
- [x] Servidor armazena as informações recebidas pelo arduino no banco de dados
- [x] TESTADO

**Comment by yagoocarvalho** [comment]
Finalizado. Falta criar o plano de testes e incluir essa feature no plano, mas os testes ad-hoc funcionaram perfeitamente

**Comment by Lucas-CG** [comment]
Eu, @brunocalou e @ducast testamos o envio do Arduino e do emulador para o servidor instanciado na Amazon. Recebemos de resposta -1 (MAC não reconhecido ou erro desconhecido) e depois código 500 (erro interno do servidor).

Avisamos ao @yagoocarvalho, ele já está ciente do problema.

**Comment by yagoocarvalho** [comment]
Falei com o Eduardo. O formato do JSON estava errado. O data é um array de
dados, e o equipamento precisa de um ID. Consertei no emulador

Em qua, 28 de jun de 2017 13:51, Lucas de Carvalho <notifications@github.com>
escreveu:

**Comment by Lucas-CG** [comment]
Ok! Devo ter esquecido dos colchetes. =)

**Comment by yagoocarvalho** [comment]
Depois de consertar o formato coloquei pra rodar no servidor e está
funcionando perfeitamente :)

Em qua, 28 de jun de 2017 15:07, Lucas de Carvalho <notifications@github.com>
escreveu:

**Comment by paulocsanz** [comment]
Acompanhar updates do Arduino na Issue #48.
