### ISSUE TITLE
Criar regras de entrada e saída de cada usuário cadastrado no MyDenox

### ISSUE THREAD

**Issue by yagoocarvalho** [ESEGroup/IssuesMonitoring#34]

**Comment by ghtravassos** [comment]
IMportante descrever o que foi feito e indicar queusuarios foram cadastrados. Onde isso esta registrado alem do MyDenox?

**Comment by yagoocarvalho** [comment]
Todos os usuários cadastrados no MyDenox tiveram as regras de entrada e saída criadas. A regra é:
Quando o usuário registrar presença/ausência, notificar o IssuesMonitoring com a mensagem [IN/OUT-user_id] (Ex: [IN-ghor], [OUT-hjer])

**Comment by ghtravassos** [comment]
@yagoocarvalho Qual artefato de projeto esta especificando isso? Note que dizer "todos os usuarios" nao ajuda muito. Quais sao os usuarios? isso precisa estar explicito. Por exemplo, se por algum motivo o MyDenox apagar, como realimentar o sistema?

**Comment by yagoocarvalho** [comment]
@ghtravassos foi criado uma página de manuais na Wiki do projeto para essas especificações. Lá temos o passo-a-passo de como cadastrar novos usuário, tanto no MyDenox como no IssuesMonitoring a fim de manter a consistência dos dados entre os sistemas 
https://github.com/ESEGroup/IssuesMonitoring/wiki/Manuais
