### ISSUE TITLE
Estruturação do banco de dados

### ISSUE THREAD

**Issue by deborabpina** [ESEGroup/IssuesMonitoring#35]
- [x] Dados do Parser
- [x] Dados de usuário do laboratório
- [x] Dados de usuário do sistema
- [x] Dados do arduino

**Comment by ghtravassos** [comment]
Esta issue não esta fechada. O modelo ainda esta em definicao e nenhum artefato foi depositdado no GIT.

**Comment by ghtravassos** [comment]
Como estamos em relação a esta questao?

**Comment by bruno-d-m** [comment]
Modelo e script de criação do banco em Python prontos
