### ISSUE TITLE
Catalogar sensores

### ISSUE THREAD

**Issue by ducast** [ESEGroup/IssuesMonitoring#36]
01 - Sensor de umidade e temperatura DHT11
02 - Sensor de movimento presença PIR
01 - Real Time Clock RTC DS3231  
01 - Real Time Clock RTC ZS-042
01 - Sensor de chuva
01 - Sensor de som KY-038 microfone
02 - Sensor de distância ultrassônico HC-SR04
01 - Sensor de chama fogo
01 - Diodo laser 5V Arduino
01 - Sensor de luz LDR
01 - Sensor de umidade do solo higrômetro
01 - Sensor de obstáculos infravermelho IR
01 - Sensor de gás MQ-2 inflamável e fumaça
02 - Módulo RF transmissor+receptor 315MHz
02 - Módulo sensor de vibração SW-420
01 - Sensor ótico reflexivo TCRT5000

**Comment by ghtravassos** [comment]
Ok. Preparar documento contendo a lista de sensores para controle interno.
