### ISSUE TITLE
Comprar sensor de temperatura para a(s) máquina(s)

### ISSUE THREAD

**Issue by ducast** [ESEGroup/IssuesMonitoring#37]

**Comment by ghtravassos** [comment]
Favor verificar se este modelo satisfaz as especificacoes: http://www.filipeflop.com/pd-1e7d0e-sensor-de-temperatura-ds18b20-a-prova-d-agua.html?ct=41d97&p=1&s=1

**Comment by ducast** [comment]
Satisfaz.

**Comment by ghtravassos** [comment]
Preciso da especificação do shield que esta faltando. Alguem poderia me enviar?

**Comment by ghtravassos** [comment]
Sensor de temperatura e controlador de corrente foram adquiridos. Devem chegar em ate 4 dias uteis. Nao foi possivel comprar rele de acionamento.

**Comment by ghtravassos** [comment]
Sensores entregues
