### ISSUE TITLE
Ler as medidas dos sensores

### ISSUE THREAD

**Issue by ducast** [ESEGroup/IssuesMonitoring#4]
Sensores:
- [x] Temperatura Ambiente
- [x] Temperatura de uma Maquina
- [x] Luminosidade do Ambiente
- [x] Umidade do Ambiente

- [x] Converter as medidas dos sensores para as unidades desejadas (Celsius, Lux, Porcentagem?)

- [x] TESTADO

**Comment by brunocalou** [comment]
Só falta a temperatura da máquina
aa7fb9cafb158a0d8bf88a090fec76ce44b4a9db
