### ISSUE TITLE
Dividir os pares para desenvolvimento e redistribuir os membros dos times

### ISSUE THREAD

**Issue by Lucas-CG** [ESEGroup/IssuesMonitoring#43]

**Comment by ghtravassos** [comment]
Quem esta responsavel por isso? Os times ja foram definidos?

**Comment by cemarciano** [comment]
Times definidos e tarefas designadas: 

Duplas
- Dupla 1: Marcelo e Silvia
- Dupla 2: Brian e Débora
- Dupla 3: Bruno Dias e Yago
- Dupla 4: Carlos e Paulo
- Trio: Bruno Calou, Eduardo e Lucas

Tarefas:
- T1: Registrar dados do Arduino no banco de dados
- T2: Identificar anomalias e notificar usuáro sobre essas alterações da zona de conforto
- T3: Edição e exclusão de usuário do laboratório e do ISSUES (faz parte do requisito de Manter registro dos usuários)
- T4: Identificar se a luz está acesa e se há pessoas na sala e notificar responsável
- T5: Modificações do template e outras melhorias de html que foram sugeridas (tudo está no documento no drive "anotações 08-05" e também especificados na issue no github
- T6: Organização da wiki
- T7: Atualização dos documentos (Manuais de Usuário, Instalação e Operação)
- T8: Atualização de diagramas, documento de requisitos e o que mais for necessário
- T9: Escrever planos de teste funcionais (Devem ser executados para release no geral, não para sprint) e pra sprint tem que ser garantido consistência, isto é, que as páginas estão consistentes com os guidelines previdos (que são do windows 7)

Distribuição das Tarefas:
- Dupla 1: T5, T9
- Dupla 2:T2, T4, T6
- Dupla 3: T1, T8
- Dupla 4: T3, T7
