### ISSUE TITLE
Modificações na página ISSUES

### ISSUE THREAD

**Issue by deborabpina** [ESEGroup/IssuesMonitoring#47]

**Comment by deborabpina** [comment]
- [x] Tirar luminosidade do cadastro
- [x] Deixar claro unidades das medidas apresentadas
- [x] Mudar ícone de Aprovar usuário e Tornar admin
- [x] Separar os cadastros que estão mostrados na página Gerenciar
- [x] Acrescentar exibição da lista de laboratórios já cadastrados

**Comment by scaroline** [comment]
O acesso web do IssuesMonitoring deve seguir o padrão de interface clássica do Windows 7.
