### ISSUE TITLE
Realizar Login para acessar o Sistema Issues Monitoring

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#5]
Ator: Usuário do Sistema / Responsável pelo Laboratório

- [x] O ator na página principal preenche o formulário exibido:
- Nome de usuário (Login)
- Senha para acesso

- [x] O ator clica no botão “Enviar” que está localizado abaixo do campo senha. 

- [x] Ao receber a confirmação do servidor, o sistema apresenta a página “Home” em caso de sucesso ou, caso contrário, o sistema apresenta uma página de erro, permitindo o retorno à tela de login.

- [x] TESTADO

**Comment by cemarciano** [comment]
Feature iniciada e aguardando o desenvolvimento do servidor: https://github.com/ESEGroup/IssuesMonitoring/commit/e136846c19678090c9ff8370acf437641fdd0cd5

**Comment by deborabpina** [comment]
Testado de acordo com os casos de teste apresentados no Plano de teste.
