### ISSUE TITLE
Acerto dos documentos de instalação e manuais

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#50]
Retirar identificação pessoal de todos os documentos. Usem nomes ficticios. Por exemplo, Guilherme Horta Travassos esta sendo usado indistintamente. Não é adequado fazer isso em documentação publica e a ser entregue para os usuarios.
Acrescentar informacao sobre administrador. Nao e possivel entender como se acessa o sistema para sua administração. Um manual de operação pode ser necessario.

**Comment by paulocsanz** [comment]
Manual de Usuário contém informações pessoais nas páginas 13 e 15.
