### ISSUE TITLE
Reorganizacao da Wiki

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#51]
- [x] Levar os itens "Manuais" e "Manual de Instalação" para dentro de "Artefatos"
- [x] Em "Home" - retirar o conteúdo sobre "Decisões de branching" e colocar em um link chamado "Decisões Técnicas". 
- [x] Levar os itens "Release 1", "Release 2 - Sprint 1" e "Release 2 - Sprint 2" para um link chamado "Planejamento"
- [x] Em "Release 2 -  Sprint 1", especificamente em "Dívidas Técnicas", sugiro um detalhamento da seguinte forma:
   Dívidas técnicas:
     -  Desenvolver manual do usuário 
     -  Desenvolver manual de instalação
     -  Verificação de consistência entre MER e diagrama de classes.
     -  Testes
          - Planejamento de testes 
          - Especificação de casos e roteiros de Testes Funcionais
          - Execução/Automatização (testes unitários e  sistemas) e Report dos testes;

- [x] Colocar todos itens na forma link, pois permite a especificação e monitoramento.

**Comment by cemarciano** [comment]
Reorganização da wiki finalizada. Melhorias podem ser feitas no futuro.
