### ISSUE TITLE
Falta Requisito para reabilitação energia apos evento de safety (alta temperatura)

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#58]
O sistema precisa restabelecer a energia no circuito de alimentação do servidro após desligamento por excesso de temperatura. Para isso, a autorizacao para religação deve ser realizada através da web, e executada por usuario autorizado (administrador).
Especificar o requisito e cenarios e garantir a implementação para a Release 3

**Comment by Lucas-CG** [comment]
O requisito agora está especificado no Documento de Requisitos e contemplado nos cenários do Arduino.
