### ISSUE TITLE
Valores default para condições de ambiente

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#59]
As condiçoes ambientais  usuais nas instalações do cliente são:

Tempo de Verificacao de presenças no laboratorio: 30 segundos
Tempo de Verificação de Condições Ambientais: 30 segundos

Temperatura minima: 20
Temperatura maxima: 26

Umidade Minima: 40%
Umidade Maxima: 75%

Desligamento de equipamento por excesso de temperatura: 55 graus, medido n interior do gabinete.

**Comment by cemarciano** [comment]
Concluída.
