### ISSUE TITLE
Autenticação do usuário

### ISSUE THREAD

**Issue by paulocsanz** [ESEGroup/IssuesMonitoring#6]
- [ ] Servidor recebe as informações de autenticação do sistema Web

- [ ] Servidor compara com as informações do repositório

- [ ] Servidor retorna ao sistema Web o resultado da autenticação

- [ ] TESTADO

**Comment by MMaestrelliLeobons** [comment]
Existem dois "Autenticação de usuário". Qual deles está correto?

**Comment by deborabpina** [comment]
Não utilizar essa issue.
