### ISSUE TITLE
Verificar relogios e sincronizacao dos sistemas

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#60]
recebi esta mensagem as 21:16, porem deveria ter sido as 00:00. Verificar status dos sistema e sincronizacao dos relogios. E importante que todos estejam sincronizados (servidor, arduino e mydenox).

-------- Mensagem encaminhada --------
Assunto: Alerta de Reset de presenças
Data: Tue, 30 May 2017 00:00:00 +0000
De: Sistema ISSUES Monitoring <cos603.issuesmonitoring@gmail.com>
Para: ght@cos.ufrj.br, ght@cos.ufrj.br

Caro usuário,
Você está recebendo essa mensagem pois se encontra marcado como 'presente' no laboratório.
Informamos que às 00:00h de hoje, todos os logs de presença foram reiniciados.
Caso ainda se encontre no laboratório, pedimos que renove seu registro de presença.

Atenciosamente, Equipe ISSUES Monitoring

**Comment by jeronimohjr** [comment]
Exato. A sincronização deve ser verificada! Além disso, acredito que existe um erro na mensagem: ao invés de "...foram reiniciados", deveria ser "serão reiniciados". Dessa forma, o envio da mensagem faz sentido.

**Comment by jeronimohjr** [comment]
Verifiquei aqui. De fato não é a mensagem que está equivocada. O log de presença já foi apagada antes do horário.

**Comment by ghtravassos** [comment]
Continuo recebendo mensagens incorretas. Isso entrou as 21:00 de ontem (6/7):
-------- Forwarded Message --------
Subject: Alerta de Reset de presenças
Date: Wed, 07 Jun 2017 00:00:00 +0000
From: Sistema ISSUES Monitoring <cos603.issuesmonitoring@gmail.com>
To: ght@cos.ufrj.br


Caro usuário,
Você está recebendo essa mensagem pois se encontra marcado como 'presente' no laboratório.
Informamos que às 00:00h de hoje, todos os logs de presença foram reiniciados.
Caso ainda se encontre no laboratório, pedimos que renove seu registro de presença.


Atenciosamente, Equipe ISSUES Monitoring

**Comment by yagoocarvalho** [comment]
As variáveis de ambiente foram trocadas e agora o servidor roda em GMT-3
