### ISSUE TITLE
Incosistencias na Interface com o Usuario

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#65]
Ainda se observam vários problemas na IU, conforme discutido com a equipe:
a) não faz sentido o termo aprovado para usuário. O correto seria autorizado (não autorizado)
b) sistema informa mensagem de ERRO quando alguma ação não pode ser executada por conta de falta de informação. Isso não é erro!
c) o uso de cores esta excessivo (estado dos botoes e acoes). Alem disso, não privilegia acessibilidade. Consider que alguns usuários podem não diferenciar mudança de cor. Ajustar interface para privilegiar tons de cinza indicando mudança de estado

**Comment by cemarciano** [comment]
Issue subdividia em outras issues.
