### ISSUE TITLE
Roteiros e casos de teste no TEstLink do projeto

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#68]
Transferir as informações de teste para o ambiente TestLink configurado para o projeto. O sistema se encontra em http://lens.cos.ufrj.br/testlink.  Por favor, façam o cadastro no ambiente e informem imediatamente a Valeria/Helvio para autorizarem o cadastro e vinculo com o projeto. 
Prazo para execução até 14/06

**Comment by cemarciano** [comment]
@bruno-d-m

**Comment by cemarciano** [comment]
@bconfessor

**Comment by jeronimohjr** [comment]
O cadastro e perfis já foram realizados.
