### ISSUE TITLE
Ações de interface inconsistente

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#71]
A utilização ou não,a de botão de confirmação para ação está confusa.  Em algumas atividades o simples fato de alterar um interruptor implica em concordancia e alteracao automatica. Em outros, alem de selecionar e confirmar tem que usar o botao de conformacao. Portanto, o modelo deve ser consistente e adotar o mesmo procedimento nas diferentes dialogos entre o usuario e o sistema.

**Comment by deborabpina** [comment]
Negociar com stakeholder.
