### ISSUE TITLE
Falta de aviso de quebra de sistema

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#75]
A execução de solicitação de presença não finaliza devido a quebra do parser. O IssuesMonitoring deve apresentar o status de execução de seus componentes e garantir que as funções que utilizam os componentes usem este estado como pre-condição de execução. Por exemplo, a lista de presenças no laboratório so pode funcionar se o parser estiver ativo. No caso, a mensagem "Não há membros presentes neste momento." só é valida SE tudo estiver funcionando e se comunicando. Caso contrario, deveria apresentar "Informação não disponível no momento. Contate o Administrador do IssuesMonitoring"

**Comment by paulocsanz** [comment]
Parser integrado ao servidor.

Só existem falhas do MyDenox, porém só existe aviso de falha, não de solução, então o sistema continuará avisando que há falha após ela ter sido solucionada. Só aparecerá como solucionada quando alguém registrar entrada ou saida no sistema.

Então se o sistema falhar quando não há usuários presentes (como no fim de semana), ficará exibindo a falha até alguém entrar novamente.

Isso é melhor que apenas exibir que não há ninguém presente?

Como lidar com falhas no sistema MyDenox?

**Comment by ghtravassos** [comment]
MAnter aviso de falha ate a correcao. Em relacao ao MyDenox deve informar que o suporte@MyDenox deve ser notificado do problema. Ver os comentarios da #77
