### ISSUE TITLE
Facilidade para ativar serviços IssuesMonitoring

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#77]
Necessário ter informação ou facilidade de como colocar os componentes do sistema IssuesMonitoring para funcionar. Por exemplo, se o parser cair, o que precisa ser feito? Se o arduino cair, o que precisa ser feito? É possivel ativar estes componentes via Web? E desativar?

**Comment by paulocsanz** [comment]
Parser integrado ao servidor.

O que deve ser feito sobre o Arduino? A resolução de problemas nele é física, portanto não há muito o que o sistema possa fazer além de avisar que há um problema.

Sobre a ativação/desativação do Arduino é possível implementar ao Sistema Web se desejado, porém levando em consideração as dívidas técnicas do módulo Arduino acredito ser melhor não desenvolver isso e focar todos os recursos para as funcionalidades já planejadas.

**Comment by ghtravassos** [comment]
Inserir comentario na pagina sobre o problema que deve haver uma intervencao fisica no equipamento (arduino) depois de detectar o problema.
Quanto ao parser ok. Apenas informar se existe problema de comunicacao.

**Comment by paulocsanz** [comment]
Mensagem de falha no Arduino exibida, resolucao de bugs na implementação em #119
