### ISSUE TITLE
Sistema nao detecta a saida de membro do Laboratorio em tempo programado

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#85]
O registro da saida do Laboratorio nao esta sendo atualizado no tempo programado para o parser. Verificar se o problema e devido ao parser, atualizacao web ou recebimento de email. A saida registrada no MyDenox:

Saída registrada 
Guilherme Horta Travassos
em 14/06/2017 11:23:00

So apareceu na interface do Issues 10 minutos depois!

**Comment by cemarciano** [comment]
Isso foi devido ao fato de que o botão que alterna entre Log de Presença e Usuários Presentes não estava programado para atualizar as informações. Agora ele já está.
