### ISSUE TITLE
Nova propriedade de laboratório: "Intervalo de Alertas"

### ISSUE THREAD

**Issue by cemarciano** [ESEGroup/IssuesMonitoring#86]
Novo atributo que especificará de quanto em quanto tempo os e-mails de aviso devem ser reenviados para os responsáveis.

- [ ] Atributo possível de ser modificado pela web
- [ ] Atributo adicionado ao banco de dados
- [ ] View+controller do atributo
- [ ] Atributo implementado no servidor

**Comment by yagoocarvalho** [comment]
Implementamos os alarmes de forma a não enviar "spam" sobre uma anomalia. Se a temperatura  está baixa, por exemplo, só será enviado um email caso haja uma anomalia diferente, como temperatura alta ou umidade, por exemplo. Portanto, não há necessidade de um tempo entre emails.
