### ISSUE TITLE
Modificar o Log de Presença

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#87]
O log de presença deve informar os registros de entrada e de saida dos usuarios, e nao apenas entrada.

**Comment by ghtravassos** [comment]
Verificar o delay entre membros presentes e log de presença. Nao pude perceber o registro de saida no log de presença no mesmo instante.

**Comment by ghtravassos** [comment]
Fazer com que a pagina seja atualizada toda vez que uma intereacao ocorra. (membros presentes ou log de presencas)

**Comment by paulocsanz** [comment]
Conteúdo atualizado após mudança de página (laboratórios, membros presentes e log de presenças)
