### ISSUE TITLE
Novos requisitos nao presentes na especificação

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#90]
Atualizar a especificação de requisitos e todos os artefatos relacionados para tornar explicitos os novos requisitos definidos para os sistema e referentes a relatorios, tratamento de desligamento e restabelecimento de funcionalidades, dentre outros.

**Comment by deborabpina** [comment]
No documento de requisitos:
RF03 - relatórios
RF13 - desligamento
RF18 - reestabelecimento de energia

**Comment by deborabpina** [comment]
@scaroline tem isso nos cenários?

**Comment by deborabpina** [comment]
@Lucas-CG @ducast isso tem nos cenários do arduino?
