### ISSUE TITLE
Issues Monitoring deve notificar existencia de usuarios cadastrados e NAO autorizados

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesMonitoring#95]
Não é possivel ao usuario (administrador) saber que existem usuarios pendentes de autorização a nçao ser que adote o comportamento de estar sempre consultando. para evitar isso, o sistema deve enviar uma notificacao (email) para os administradores informando sobre a existencia de cadastroa sem autorizacao.

**Comment by cemarciano** [comment]
O sistema já faz isso. Todos os administradores recebem uma mensagem (e-mail) quando um novo usuário se cadastra.
